---
permalink: install-windows/task_uninstall_unified_manager_win.html 
sidebar: sidebar 
keywords: uninstall, unified manager 
summary: 'È possibile disinstallare Unified Manager utilizzando la procedura guidata programmi e funzionalità o eseguendo una disinstallazione automatica dall"interfaccia della riga di comando.' 
---
= Disinstallazione di Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/
:pp: &#43;&#43;


[role="lead"]
È possibile disinstallare Unified Manager utilizzando la procedura guidata programmi e funzionalità o eseguendo una disinstallazione automatica dall'interfaccia della riga di comando.

*Cosa ti serve*

* È necessario disporre dei privilegi di amministratore di Windows.
* Tutti i cluster (origini dati) devono essere rimossi dal server Unified Manager prima di disinstallare il software.


.Fasi
. Disinstallare Unified Manager scegliendo una delle seguenti opzioni:
+
[cols="2*"]
|===
| Per disinstallare Unified Manager da... | Quindi... 


 a| 
Wizard programmi e funzionalità:
| : 


 a| 
.. Accedere a *pannello di controllo* > *programmi e funzionalità*.
.. Selezionare Active IQ Unified Manager e fare clic su *Disinstalla*.

 a| 
Riga di comando

|===
+
Se il controllo dell'account utente (UAC) è attivato sul server e si è connessi come utente di dominio, è necessario utilizzare il metodo di disinstallazione dalla riga di comando.

+
Unified Manager viene disinstallato dal sistema.

. Disinstallare i seguenti pacchetti e dati di terze parti che non vengono rimossi durante la disinstallazione di Unified Manager:
+
** Pacchetti di terze parti: JRE, MySQL, Microsoft Visual C& 43; 43; 2015 Redistributable e 7zip
** Dati dell'applicazione MySQL generati da Unified Manager
** Log delle applicazioni e contenuto della directory dei dati delle applicazioni



