---
permalink: events/task_upload_new_active_iq_rules_file.html 
sidebar: sidebar 
keywords: upload, new, active iq, rules, file 
summary: Unified Manager verifica automaticamente la presenza di un nuovo file di regole Active IQ e scarica un nuovo file quando sono presenti regole più recenti. Tuttavia, nei siti senza accesso alla rete esterna, è necessario caricare manualmente il file di regole. 
---
= Caricamento di un nuovo file di regole Active IQ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager verifica automaticamente la presenza di un nuovo file di regole Active IQ e scarica un nuovo file quando sono presenti regole più recenti. Tuttavia, nei siti senza accesso alla rete esterna, è necessario caricare manualmente il file di regole.

*Cosa ti serve*

* È necessario attivare la funzione di reporting degli eventi Active IQ.
* È necessario scaricare il file di regole dal sito del supporto NetApp.


Si consiglia di scaricare un nuovo file di regole circa una volta al mese per assicurarsi che i sistemi storage siano protetti e che funzionino in modo ottimale. Il file di regole si trova in: http://mysupport.netapp.com/NOW/public/unified_manager/bin/secure_rules.zip[]

.Fasi
. Su un computer con accesso alla rete, accedere al sito del supporto NetApp e scaricare le regole correnti `.zip` file.
. Trasferire il file di regole su alcuni supporti che è possibile inserire nell'area protetta e copiarlo su un sistema nell'area protetta.
. Nel riquadro di navigazione a sinistra, fare clic su *Storage Management* > *Event Setup*.
. Nella pagina *impostazione evento*, fare clic sul pulsante *regole di caricamento*.
. Nella finestra di dialogo *regole di caricamento*, selezionare le regole e selezionarle `.zip` File scaricato e fare clic su *carica*.
+
Questo processo può richiedere alcuni minuti.



Il file di regole viene decompresso sul server Unified Manager. Dopo che i cluster gestiti generano un file AutoSupport dopo la mezzanotte, Unified Manager verificherà i cluster in base al file di regole e genererà nuovi eventi di rischio e incidenti, se necessario.

Per ulteriori informazioni, consultare l'articolo della Knowledge base (KB):link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/Active_IQ_Unified_Manager/How_to_update_AIQCASecure_rules_manually_in_Active_IQ_Unified_Manager["Come aggiornare manualmente le regole AIQCASecure in Active IQ Unified Manager"^].
